# Generated by Django 2.1.7 on 2024-07-07 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0002_auto_20240707_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalExaminer', models.FloatField()),
                ('supervisor', models.FloatField()),
                ('staff', models.FloatField()),
                ('peon', models.FloatField()),
                ('tax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defenseDate', models.CharField(max_length=100)),
                ('studentBatch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinatorName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.Teacher')),
                ('programName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programCoordinator', to='college.Programme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rollNumber', models.CharField(max_length=30)),
                ('thesisTitle', models.CharField(blank=True, max_length=500, null=True)),
                ('midterm', models.BooleanField(blank=True, default=False)),
                ('final', models.BooleanField(blank=True, default=False)),
                ('internalMarks', models.IntegerField(blank=True, null=True)),
                ('finalMarks', models.IntegerField(blank=True, null=True)),
                ('totalMarks', models.IntegerField(blank=True, null=True)),
                ('examRollNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('examiner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.Expert')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.Teacher')),
            ],
        ),
    ]
