# Generated by Django 2.1.7 on 2019-08-18 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Examiner',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.AlterField(
            model_name='admin',
            name='coordinatorName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.Teacher'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='programName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.Programme'),
        ),
    ]
