# Generated by Django 2.1.7 on 2019-08-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0003_auto_20190818_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='programName',
        ),
    ]
