# Generated by Django 2.0.6 on 2019-08-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_coordinator_programname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='remove',
        ),
    ]
